<?php
/**
 * OfflineTicketTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  InteractiveTicketing
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Developer API
 *
 * Get your API Key from the [Dashboard](/dashboard/).<br/>Send all API requests with http header `X-API-Key: YOUR-API-KEY-HERE`.<br/>Base URL: `https://secure.interactiveticketing.com/developers/api/v2`<br/>Contact support@interactiveticketing.com for help.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.10
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace InteractiveTicketing;

/**
 * OfflineTicketTest Class Doc Comment
 *
 * @category    Class
 * @description OfflineTicket
 * @package     InteractiveTicketing
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OfflineTicketTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OfflineTicket"
     */
    public function testOfflineTicket()
    {
    }

    /**
     * Test attribute "offlineTicketId"
     */
    public function testPropertyOfflineTicketId()
    {
    }

    /**
     * Test attribute "testTicket"
     */
    public function testPropertyTestTicket()
    {
    }

    /**
     * Test attribute "barcode"
     */
    public function testPropertyBarcode()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "details"
     */
    public function testPropertyDetails()
    {
    }

    /**
     * Test attribute "slotDate"
     */
    public function testPropertySlotDate()
    {
    }

    /**
     * Test attribute "slotTime"
     */
    public function testPropertySlotTime()
    {
    }

    /**
     * Test attribute "seatCustom1"
     */
    public function testPropertySeatCustom1()
    {
    }

    /**
     * Test attribute "seatCustom2"
     */
    public function testPropertySeatCustom2()
    {
    }

    /**
     * Test attribute "seatSection"
     */
    public function testPropertySeatSection()
    {
    }

    /**
     * Test attribute "seatRow"
     */
    public function testPropertySeatRow()
    {
    }

    /**
     * Test attribute "seatNumber"
     */
    public function testPropertySeatNumber()
    {
    }

    /**
     * Test attribute "canceled"
     */
    public function testPropertyCanceled()
    {
    }

    /**
     * Test attribute "scans"
     */
    public function testPropertyScans()
    {
    }

    /**
     * Test attribute "scanPointConfig"
     */
    public function testPropertyScanPointConfig()
    {
    }
}
