<?php
/**
 * OrderTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  InteractiveTicketing
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Developer API
 *
 * Get your API Key from the [Dashboard](/dashboard/).<br/>Send all API requests with http header `X-API-Key: YOUR-API-KEY-HERE`.<br/>Base URL: `https://secure.interactiveticketing.com/developers/api/v4`<br/>Contact support@interactiveticketing.com for help.
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.38
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace InteractiveTicketing;

/**
 * OrderTest Class Doc Comment
 *
 * @category    Class
 * @description Order
 * @package     InteractiveTicketing
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Order"
     */
    public function testOrder()
    {
    }

    /**
     * Test attribute "orderId"
     */
    public function testPropertyOrderId()
    {
    }

    /**
     * Test attribute "dateTime"
     */
    public function testPropertyDateTime()
    {
    }

    /**
     * Test attribute "testOrder"
     */
    public function testPropertyTestOrder()
    {
    }

    /**
     * Test attribute "orderType"
     */
    public function testPropertyOrderType()
    {
    }

    /**
     * Test attribute "firstName"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "lastName"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "mobilePhone"
     */
    public function testPropertyMobilePhone()
    {
    }

    /**
     * Test attribute "street"
     */
    public function testPropertyStreet()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "stateProvince"
     */
    public function testPropertyStateProvince()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "postalCode"
     */
    public function testPropertyPostalCode()
    {
    }

    /**
     * Test attribute "fees"
     */
    public function testPropertyFees()
    {
    }

    /**
     * Test attribute "taxes"
     */
    public function testPropertyTaxes()
    {
    }

    /**
     * Test attribute "donations"
     */
    public function testPropertyDonations()
    {
    }

    /**
     * Test attribute "grandTotal"
     */
    public function testPropertyGrandTotal()
    {
    }

    /**
     * Test attribute "coupons"
     */
    public function testPropertyCoupons()
    {
    }

    /**
     * Test attribute "couponsTotal"
     */
    public function testPropertyCouponsTotal()
    {
    }

    /**
     * Test attribute "iPAddress"
     */
    public function testPropertyIPAddress()
    {
    }

    /**
     * Test attribute "browserName"
     */
    public function testPropertyBrowserName()
    {
    }

    /**
     * Test attribute "browserDevice"
     */
    public function testPropertyBrowserDevice()
    {
    }

    /**
     * Test attribute "sourceCode"
     */
    public function testPropertySourceCode()
    {
    }

    /**
     * Test attribute "searchTag"
     */
    public function testPropertySearchTag()
    {
    }

    /**
     * Test attribute "survey"
     */
    public function testPropertySurvey()
    {
    }

    /**
     * Test attribute "transactions"
     */
    public function testPropertyTransactions()
    {
    }

    /**
     * Test attribute "tickets"
     */
    public function testPropertyTickets()
    {
    }

    /**
     * Test attribute "posCashierName"
     */
    public function testPropertyPosCashierName()
    {
    }

    /**
     * Test attribute "suspectFlags"
     */
    public function testPropertySuspectFlags()
    {
    }

    /**
     * Test attribute "isSuspicious"
     */
    public function testPropertyIsSuspicious()
    {
    }

    /**
     * Test attribute "suspiciousResolved"
     */
    public function testPropertySuspiciousResolved()
    {
    }
}
