<?php
/**
 * ScanResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  InteractiveTicketing
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Developer API
 *
 * Get your API Key from the [Dashboard](/dashboard/).<br/>Send all API requests with http header `X-API-Key: YOUR-API-KEY-HERE`.<br/>Base URL: `https://secure.interactiveticketing.com/developers/api/v2`<br/>Contact support@interactiveticketing.com for help.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.10
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace InteractiveTicketing;

/**
 * ScanResponseTest Class Doc Comment
 *
 * @category    Class
 * @description ScanResponse
 * @package     InteractiveTicketing
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ScanResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ScanResponse"
     */
    public function testScanResponse()
    {
    }

    /**
     * Test attribute "valid"
     */
    public function testPropertyValid()
    {
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "details"
     */
    public function testPropertyDetails()
    {
    }

    /**
     * Test attribute "scanTime"
     */
    public function testPropertyScanTime()
    {
    }

    /**
     * Test attribute "method"
     */
    public function testPropertyMethod()
    {
    }

    /**
     * Test attribute "barcode"
     */
    public function testPropertyBarcode()
    {
    }

    /**
     * Test attribute "scanPointId"
     */
    public function testPropertyScanPointId()
    {
    }

    /**
     * Test attribute "testMode"
     */
    public function testPropertyTestMode()
    {
    }

    /**
     * Test attribute "event"
     */
    public function testPropertyEvent()
    {
    }

    /**
     * Test attribute "ticket"
     */
    public function testPropertyTicket()
    {
    }

    /**
     * Test attribute "offlineTicket"
     */
    public function testPropertyOfflineTicket()
    {
    }

    /**
     * Test attribute "thirdPartyTicket"
     */
    public function testPropertyThirdPartyTicket()
    {
    }
}
