<?php
/**
 * TicketTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  InteractiveTicketing
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Developer API
 *
 * Get your API Key from the [Dashboard](/dashboard/).<br/>Send all API requests with http header `X-API-Key: YOUR-API-KEY-HERE`.<br/>Base URL: `https://secure.interactiveticketing.com/developers/api/v4`<br/>Contact support@interactiveticketing.com for help.
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.38
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace InteractiveTicketing;

/**
 * TicketTest Class Doc Comment
 *
 * @category    Class
 * @description Ticket
 * @package     InteractiveTicketing
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TicketTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Ticket"
     */
    public function testTicket()
    {
    }

    /**
     * Test attribute "ticketId"
     */
    public function testPropertyTicketId()
    {
    }

    /**
     * Test attribute "orderId"
     */
    public function testPropertyOrderId()
    {
    }

    /**
     * Test attribute "barcode"
     */
    public function testPropertyBarcode()
    {
    }

    /**
     * Test attribute "canceled"
     */
    public function testPropertyCanceled()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "details"
     */
    public function testPropertyDetails()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "slotDate"
     */
    public function testPropertySlotDate()
    {
    }

    /**
     * Test attribute "slotTime"
     */
    public function testPropertySlotTime()
    {
    }

    /**
     * Test attribute "slotAllDay"
     */
    public function testPropertySlotAllDay()
    {
    }

    /**
     * Test attribute "nameOnTicket"
     */
    public function testPropertyNameOnTicket()
    {
    }

    /**
     * Test attribute "seatEventTitle"
     */
    public function testPropertySeatEventTitle()
    {
    }

    /**
     * Test attribute "seatVenueTitle"
     */
    public function testPropertySeatVenueTitle()
    {
    }

    /**
     * Test attribute "seatSection"
     */
    public function testPropertySeatSection()
    {
    }

    /**
     * Test attribute "seatCustom1"
     */
    public function testPropertySeatCustom1()
    {
    }

    /**
     * Test attribute "seatCustom2"
     */
    public function testPropertySeatCustom2()
    {
    }

    /**
     * Test attribute "seatRow"
     */
    public function testPropertySeatRow()
    {
    }

    /**
     * Test attribute "seatRowLabel"
     */
    public function testPropertySeatRowLabel()
    {
    }

    /**
     * Test attribute "seatNumber"
     */
    public function testPropertySeatNumber()
    {
    }

    /**
     * Test attribute "seatNumberLabel"
     */
    public function testPropertySeatNumberLabel()
    {
    }

    /**
     * Test attribute "seatText"
     */
    public function testPropertySeatText()
    {
    }

    /**
     * Test attribute "noPrint"
     */
    public function testPropertyNoPrint()
    {
    }

    /**
     * Test attribute "noBarcode"
     */
    public function testPropertyNoBarcode()
    {
    }

    /**
     * Test attribute "discount"
     */
    public function testPropertyDiscount()
    {
    }

    /**
     * Test attribute "fee"
     */
    public function testPropertyFee()
    {
    }

    /**
     * Test attribute "tax"
     */
    public function testPropertyTax()
    {
    }

    /**
     * Test attribute "refund"
     */
    public function testPropertyRefund()
    {
    }

    /**
     * Test attribute "promoCode"
     */
    public function testPropertyPromoCode()
    {
    }

    /**
     * Test attribute "promoName"
     */
    public function testPropertyPromoName()
    {
    }

    /**
     * Test attribute "promoDescription"
     */
    public function testPropertyPromoDescription()
    {
    }

    /**
     * Test attribute "department"
     */
    public function testPropertyDepartment()
    {
    }

    /**
     * Test attribute "scans"
     */
    public function testPropertyScans()
    {
    }

    /**
     * Test attribute "scanPointConfig"
     */
    public function testPropertyScanPointConfig()
    {
    }
}
