<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  InteractiveTicketing
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Developer API
 *
 * Get your API Key from the [Dashboard](/dashboard/).<br/>Send all API requests with http header `X-API-Key: YOUR-API-KEY-HERE`.<br/>Base URL: `https://secure.interactiveticketing.com/developers/api/v1`<br/>Contact support@interactiveticketing.com for help.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.7
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace InteractiveTicketing;

use InteractiveTicketing\Configuration;
use InteractiveTicketing\ApiException;
use InteractiveTicketing\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  InteractiveTicketing
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for eventsEventIdGet
     *
     * Single Event.
     *
     */
    public function testEventsEventIdGet()
    {
    }

    /**
     * Test case for eventsEventIdOrdersGet
     *
     * Search Orders.
     *
     */
    public function testEventsEventIdOrdersGet()
    {
    }

    /**
     * Test case for eventsEventIdOrdersOrderIdGet
     *
     * Single Order.
     *
     */
    public function testEventsEventIdOrdersOrderIdGet()
    {
    }

    /**
     * Test case for eventsGet
     *
     * All Events.
     *
     */
    public function testEventsGet()
    {
    }
}
